git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# This uses automatically the latest version of go
go:
  - master

# This provides the latest version of Hugo to Travis CI
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

# This commands builds your website on travis
script:
  - hugo 

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: brtknr/brtknr.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: b.kunwar@gmail.com
  name: "brtknr"
  on:
    branch: master
