# Base URL
baseurl:  # the subpath of your site, e.g. /blog/

# Site live URL
url: http://localhost:4000 # the base hostname & protocol for your site

# Mathjax
mathjax_url: http://localhost:8000/MathJax.js?config=TeX-AMS-MML_HTMLorMML