# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# Site live URL
url: http://brtknr.com

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Bharat Kunwar,
  # Little description about your site
  description: his experiences and opinions, usually about technology, politics and research.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   Harmony is a free responsive jekyll theme by Gayan Virajith
   and Maheshika Lakmali. Sourced on Github - 
   https://github.com/gayanvirajith/harmony
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Bharat Kunwar
    email: b.kunwar@gmail.com
    url: http://brtknr.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: brtknr
    twitter: brtknr
    facebook: brtknr
    gplus: 
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown

# Github complains about pygment highlighter so we are changing this to rouge instead.
# highlighter: rouge 

# Permalinks
permalink:        pretty

exclude: 
  - brtknr.sublime-project
  - brtknr.sublime-workspace
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - serve.sh

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass