name: Link Snitch

on:
  workflow_run:
    workflows:
      - "GitHub Pages"
    types:
      - completed

env:
  URL: https://brtknr.github.io
  FILENAME: report.yaml
  CONFIG: hydra.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
