name: Link Snitch

on:
  workflow_run:
    workflows:
      - "GitHub Pages"
    types:
      - completed

env:
  URL: https://brtknr.github.io
  CONFIG: hydra.yaml

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
    steps:
      - name: Check out master to get config file
        uses: actions/checkout@master
        fetch-depth: 1
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
